name: Bot_SCM_Tiap_Malam
on:
  schedule:
    - cron: '0 17 * * *' # Jam 00:00 WIB
  workflow_dispatch: # Supaya bisa kita klik 'Run' manual buat ngetes

jobs:
  eksekusi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Library
        run: pip install requests selenium undetected-chromedriver
      - name: Jalankan Bot
        run: python bot_scm.py
