name: Bot_SCM_Tiap_Malam
on:
  schedule:
    # 10:30 UTC sama dengan 18:30 WITA
    - cron: '13 18 * * *'
    # 16:14 UTC sama dengan 00:14 WITA
    - cron: '14 00 * * *'
  workflow_dispatch:

jobs:
  eksekusi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install Library
        run: pip install requests selenium undetected-chromedriver pandas openpyxl
        
      - name: Jalankan Bot
        # Bagian env ini yang WAJIB ada supaya bot bisa baca Secret kamu
        env:
          EMAIL_SCM: ${{ secrets.EMAIL_SCM }}
          PASS_SCM: ${{ secrets.PASS_SCM }}
        run: python bot_scm.py
